"""Theme profiles and color systems for YTUI."""

from typing import Dict, List, Optional, Tuple
from textual.app import App
from textual.theme import Theme


# ---------------------------------------------------------------------------
# Handcrafted Aesthetic Theme Profiles
# ---------------------------------------------------------------------------

CUSTOM_THEMES: List[Theme] = [
    # 1. Shadcn Zinc (Sleek Obsidian & Titanium)
    Theme(
        name="shadcn-zinc",
        primary="#fafafa",
        secondary="#a1a1aa",
        accent="#38bdf8",
        warning="#fbbf24",
        error="#f43f5e",
        success="#22c55e",
        foreground="#f4f4f5",
        background="#09090b",
        surface="#121215",
        panel="#1c1c21",
        boost="#27272e",
        dark=True,
        variables={
            "border": "#27272e",
            "border-focus": "#fafafa",
            "text-muted": "#858591",
            "input-cursor-background": "#fafafa",
            "input-cursor-foreground": "#09090b",
        },
    ),
    # 2. Tokyo Night (Cyberpunk Japanese dusk)
    Theme(
        name="tokyo-night",
        primary="#7aa2f7",
        secondary="#bb9af7",
        accent="#7dcfff",
        warning="#e0af68",
        error="#f7768e",
        success="#9ece6a",
        foreground="#c0caf5",
        background="#1a1b26",
        surface="#202334",
        panel="#292e42",
        boost="#3b4261",
        dark=True,
        variables={
            "border": "#3b4261",
            "border-focus": "#7aa2f7",
            "text-muted": "#848eb8",
            "input-cursor-background": "#7aa2f7",
            "input-cursor-foreground": "#1a1b26",
        },
    ),
    # 3. Catppuccin Mocha (Smooth soothing pastel dark)
    Theme(
        name="catppuccin-mocha",
        primary="#cba6f7",
        secondary="#89b4fa",
        accent="#f5c2e7",
        warning="#f9e2af",
        error="#f38ba8",
        success="#a6e3a1",
        foreground="#cdd6f4",
        background="#181825",
        surface="#1e1e2e",
        panel="#28283d",
        boost="#36374f",
        dark=True,
        variables={
            "border": "#45475a",
            "border-focus": "#cba6f7",
            "text-muted": "#a6adc8",
            "input-cursor-background": "#cba6f7",
            "input-cursor-foreground": "#11111b",
        },
    ),
    # 4. Dracula Pro (Vibrant gothic dark)
    Theme(
        name="dracula",
        primary="#bd93f9",
        secondary="#8be9fd",
        accent="#ff79c6",
        warning="#f1fa8c",
        error="#ff5555",
        success="#50fa7b",
        foreground="#f8f8f2",
        background="#21222c",
        surface="#282a36",
        panel="#343746",
        boost="#44475a",
        dark=True,
        variables={
            "border": "#44475a",
            "border-focus": "#bd93f9",
            "text-muted": "#7a88cf",
            "input-cursor-background": "#bd93f9",
            "input-cursor-foreground": "#282a36",
        },
    ),
    # 5. Nord Polar (Arctic polar night & glacial frost)
    Theme(
        name="nord",
        primary="#88c0d0",
        secondary="#81a1c1",
        accent="#8fbcbb",
        warning="#ebcb8b",
        error="#bf616a",
        success="#a3be8c",
        foreground="#eceff4",
        background="#242933",
        surface="#2e3440",
        panel="#3b4252",
        boost="#4c566a",
        dark=True,
        variables={
            "border": "#434c5e",
            "border-focus": "#88c0d0",
            "text-muted": "#96a5bd",
            "input-cursor-background": "#88c0d0",
            "input-cursor-foreground": "#2e3440",
        },
    ),
    # 6. Gruvbox Dark (Warm retro vintage programmer)
    Theme(
        name="gruvbox",
        primary="#fabd2f",
        secondary="#8ec07c",
        accent="#fe8019",
        warning="#fabd2f",
        error="#fb4934",
        success="#b8bb26",
        foreground="#ebdbb2",
        background="#1d2021",
        surface="#282828",
        panel="#32302f",
        boost="#3c3836",
        dark=True,
        variables={
            "border": "#504945",
            "border-focus": "#fabd2f",
            "text-muted": "#a89984",
            "input-cursor-background": "#fabd2f",
            "input-cursor-foreground": "#282828",
        },
    ),
    # 7. Monokai Pro (Ultra-vibrant high contrast charcoal)
    Theme(
        name="monokai",
        primary="#ffd866",
        secondary="#78dce8",
        accent="#ff6188",
        warning="#fc9867",
        error="#ff6188",
        success="#a9dc76",
        foreground="#fcfcfa",
        background="#19181a",
        surface="#221f22",
        panel="#2d2a2e",
        boost="#3a383d",
        dark=True,
        variables={
            "border": "#403e41",
            "border-focus": "#ffd866",
            "text-muted": "#939293",
            "input-cursor-background": "#ffd866",
            "input-cursor-foreground": "#19181a",
        },
    ),
    # 8. Cyberpunk Neon (Night City laser cyan & hot pink)
    Theme(
        name="cyberpunk-neon",
        primary="#00f0ff",
        secondary="#ff0055",
        accent="#fcee0a",
        warning="#fcee0a",
        error="#ff0055",
        success="#00ff66",
        foreground="#e0f8ff",
        background="#08080d",
        surface="#120c22",
        panel="#1c1236",
        boost="#2d1d54",
        dark=True,
        variables={
            "border": "#3f1b73",
            "border-focus": "#00f0ff",
            "text-muted": "#9483b3",
            "input-cursor-background": "#00f0ff",
            "input-cursor-foreground": "#08080d",
        },
    ),
    # 9. Midnight Amethyst (Deep cosmic obsidian purple)
    Theme(
        name="midnight-amethyst",
        primary="#c084fc",
        secondary="#38bdf8",
        accent="#e879f9",
        warning="#fbbf24",
        error="#f43f5e",
        success="#34d399",
        foreground="#f3e8ff",
        background="#090714",
        surface="#130e28",
        panel="#1e163d",
        boost="#2e2159",
        dark=True,
        variables={
            "border": "#3b2d69",
            "border-focus": "#c084fc",
            "text-muted": "#9d8bb8",
            "input-cursor-background": "#c084fc",
            "input-cursor-foreground": "#090714",
        },
    ),
    # 10. Matrix Emerald (Deep hacker terminal pine & neon green)
    Theme(
        name="matrix-emerald",
        primary="#00ff88",
        secondary="#38ef7d",
        accent="#80ffdb",
        warning="#f59e0b",
        error="#f87171",
        success="#00ff88",
        foreground="#e6fff2",
        background="#040d07",
        surface="#091b11",
        panel="#0f2b1c",
        boost="#17402a",
        dark=True,
        variables={
            "border": "#1b5235",
            "border-focus": "#00ff88",
            "text-muted": "#4ade80",
            "input-cursor-background": "#00ff88",
            "input-cursor-foreground": "#040d07",
        },
    ),
    # 11. Rosé Pine (Warm aesthetic dusk sanctuary)
    Theme(
        name="rose-pine",
        primary="#ebbcba",
        secondary="#31748f",
        accent="#c4a7e7",
        warning="#f6c177",
        error="#eb6f92",
        success="#9ccfd8",
        foreground="#e0def4",
        background="#14121e",
        surface="#191724",
        panel="#211e33",
        boost="#2b2842",
        dark=True,
        variables={
            "border": "#312d4a",
            "border-focus": "#ebbcba",
            "text-muted": "#9994b8",
            "input-cursor-background": "#ebbcba",
            "input-cursor-foreground": "#14121e",
        },
    ),
    # 12. Solarized Dark (Classic oceanic teal precision)
    Theme(
        name="solarized-dark",
        primary="#2aa198",
        secondary="#268bd2",
        accent="#6c71c4",
        warning="#b58900",
        error="#dc322f",
        success="#859900",
        foreground="#93a1a1",
        background="#00212b",
        surface="#002b36",
        panel="#073642",
        boost="#0f4552",
        dark=True,
        variables={
            "border": "#0e4b5c",
            "border-focus": "#2aa198",
            "text-muted": "#657b83",
            "input-cursor-background": "#2aa198",
            "input-cursor-foreground": "#002b36",
        },
    ),
    # 13. Synthwave '84 (Neon 80s Sunset)
    Theme(
        name="synthwave-84",
        primary="#ff7edb",
        secondary="#36f9f6",
        accent="#fe4450",
        warning="#fede5d",
        error="#fe4450",
        success="#72f1b8",
        foreground="#fdfdfd",
        background="#1f182f",
        surface="#261c3b",
        panel="#32244f",
        boost="#44326b",
        dark=True,
        variables={
            "border": "#493574",
            "border-focus": "#ff7edb",
            "text-muted": "#9d8bb8",
            "input-cursor-background": "#ff7edb",
            "input-cursor-foreground": "#1f182f",
        },
    ),
    # 14. OLED Jet Black (Pure 100% black with sapphire accents)
    Theme(
        name="oled-black",
        primary="#38bdf8",
        secondary="#818cf8",
        accent="#f472b6",
        warning="#fbbf24",
        error="#f43f5e",
        success="#34d399",
        foreground="#ffffff",
        background="#000000",
        surface="#0a0a0c",
        panel="#141418",
        boost="#202026",
        dark=True,
        variables={
            "border": "#272730",
            "border-focus": "#38bdf8",
            "text-muted": "#787885",
            "input-cursor-background": "#38bdf8",
            "input-cursor-foreground": "#000000",
        },
    ),
    # 15. Catppuccin Latte (Warm modern pastel light)
    Theme(
        name="catppuccin-latte",
        primary="#8839ef",
        secondary="#1e66f5",
        accent="#179299",
        warning="#df8e1d",
        error="#d20f39",
        success="#40a02b",
        foreground="#4c4f69",
        background="#e6e9ef",
        surface="#eff1f5",
        panel="#dce0e8",
        boost="#ccd0da",
        dark=False,
        variables={
            "border": "#bcc0cc",
            "border-focus": "#8839ef",
            "text-muted": "#6c6f85",
            "input-cursor-background": "#8839ef",
            "input-cursor-foreground": "#eff1f5",
        },
    ),
    # 16. Solarized Light (Clean parchment & slate)
    Theme(
        name="solarized-light",
        primary="#268bd2",
        secondary="#2aa198",
        accent="#d33682",
        warning="#b58900",
        error="#dc322f",
        success="#859900",
        foreground="#586e75",
        background="#f5eed6",
        surface="#fdf6e3",
        panel="#eee8d5",
        boost="#e0d8c3",
        dark=False,
        variables={
            "border": "#d3cbb7",
            "border-focus": "#268bd2",
            "text-muted": "#839496",
            "input-cursor-background": "#268bd2",
            "input-cursor-foreground": "#fdf6e3",
        },
    ),
    # 17. Titanium Clean Light (Ultra-crisp modern light)
    Theme(
        name="titanium-light",
        primary="#2563eb",
        secondary="#0284c7",
        accent="#7c3aed",
        warning="#d97706",
        error="#dc2626",
        success="#16a34a",
        foreground="#0f172a",
        background="#ffffff",
        surface="#f8fafc",
        panel="#f1f5f9",
        boost="#e2e8f0",
        dark=False,
        variables={
            "border": "#cbd5e1",
            "border-focus": "#2563eb",
            "text-muted": "#64748b",
            "input-cursor-background": "#2563eb",
            "input-cursor-foreground": "#ffffff",
        },
    ),
]


# Theme select options tuple list (Label, ID)
THEME_OPTIONS: List[Tuple[str, str]] = [
    ("Shadcn Zinc (Dark)", "shadcn-zinc"),
    ("Tokyo Night", "tokyo-night"),
    ("Catppuccin Mocha", "catppuccin-mocha"),
    ("Dracula Pro", "dracula"),
    ("Nord Polar", "nord"),
    ("Gruvbox Dark", "gruvbox"),
    ("Monokai Pro", "monokai"),
    ("Cyberpunk Neon", "cyberpunk-neon"),
    ("Midnight Amethyst", "midnight-amethyst"),
    ("Matrix Emerald", "matrix-emerald"),
    ("Rosé Pine", "rose-pine"),
    ("Solarized Dark", "solarized-dark"),
    ("Synthwave '84", "synthwave-84"),
    ("OLED Jet Black", "oled-black"),
    ("Catppuccin Latte (Light)", "catppuccin-latte"),
    ("Solarized Light", "solarized-light"),
    ("Titanium Light", "titanium-light"),
]


def register_all_themes(app: App) -> None:
    """Register all custom themes into the Textual application instance."""
    for theme in CUSTOM_THEMES:
        try:
            app.register_theme(theme)
        except Exception:
            pass


def get_theme_names() -> List[str]:
    """Return all available theme IDs."""
    return [theme_id for _, theme_id in THEME_OPTIONS]
